version: "3"

services:

  wpmongo:
    container_name: webprotege-mongodb
    image: mongo:4.1-bionic
    restart: unless-stopped
    volumes: 
      - /data/webprotege/mongodb:/data/db

  webprotege:
    container_name: webprotege
    image: protegeproject/webprotege
    depends_on:
      - wpmongo
    restart: unless-stopped
    environment:
      - webprotege.mongodb.host=wpmongo
      - VIRTUAL_HOST=protege.137.120.31.101.nip.io
      - LETSENCRYPT_HOST=protege.137.120.31.101.nip.io
      - VIRTUAL_PORT=8080
    volumes: 
      - /data/webprotege/data:/srv/webprotege
    # ports:
    #   - 5000:8080

